[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "cancun"
ignored_warnings_from = ["lib"]
compilation_restrictions = [
  { paths = "src/ArchetypeBatch.sol", version = "=0.8.36" },
  { paths = "src/ArchetypeBatchV100.sol", version = "=0.8.36" },
  { paths = "src/ArchetypePayouts.sol", version = "=0.8.36" },
  { paths = "src/AffiliateSignerRegistry.sol", version = "=0.8.36" },
  { paths = "src/MintFeeRegistry.sol", version = "=0.8.36" },
]

remappings = [
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-v4-contracts-upgradeable/contracts/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "openzeppelin-v4/=lib/openzeppelin-v4-contracts/contracts/",
  "openzeppelin-v4-upgradeable/=lib/openzeppelin-v4-contracts-upgradeable/contracts/",
  "erc721a-upgradeable/=lib/ERC721A-Upgradeable/",
  "solady/=lib/solady/",
  "dn404/=lib/dn404/",
  "forge-std/=lib/forge-std/src/",
]
